### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [AetheryNA/google-scraper#48]
Hello Naveed 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now completed the first round of code reviews on the code challenge. Your efforts in implementing both unit and UI tests are duly noted. Please note that more issues could be raised, but we aim to keep the process short. The goal of the code review process is to simulate how we would work together 😁 

Please have a check on the open issues and looking forward for your feedback.

**Comment by AetheryNA** [comment]
Thank you for taking the time to review my project. I'll take a look at all the issues you've left on my project! Looking forward to seeing your feedback after the PRs have been merged 😸

**Comment by olivierobert** [comment]
Thank you @AetheryNA, for the several fixes and feedback on all open issues. Some of the suggestions would require more time for you to implement. As we strive to keep the recruitment process as short as possible, let's close this code review process as-is 😁 We have collected sufficient information for us to finalize your assessment in this stage.
