### ISSUE TITLE
[Chore] Ensure controller exceptions are used consistently

### ISSUE THREAD

**Issue by olivierobert** [AetheryNA/google-scraper#49]
## Issue

Nest.JS provides [many built-in exceptions](https://docs.nestjs.com/exception-filters#built-in-http-exceptions). This has been used in:

https://github.com/AetheryNA/google-scraper/blob/7f6cb6cadc2477961b45ccba7ca448255abe45de/src/controllers/user.controller.ts#L86-L88

But not in:

https://github.com/AetheryNA/google-scraper/blob/7f6cb6cadc2477961b45ccba7ca448255abe45de/src/controllers/dashboard.controller.ts#L56-L60

## Expected

Ensure all controllers use the appropriate exceptions. In the above example `UnprocessableEntityException` would be the correct 🤓

**Comment by olivierobert** [comment]
Another example would:

https://github.com/AetheryNA/google-scraper/blob/7f6cb6cadc2477961b45ccba7ca448255abe45de/src/controllers/user.controller.ts#L54-L58

Where `ConflictException` would be the correct one.

**Comment by AetheryNA** [comment]
Thanks for your suggestions 😸 

I've changed the error exceptions that you've suggested for these controllers. I could add a Not Found exception and improve the results service as my HTTP exception filter catches these errors and sends it back. 

What do you think about this implementation? 🤔

**Comment by AetheryNA** [comment]
I've created a PR #57 that implemented your suggestions 😸

**Comment by AetheryNA** [comment]
#58  Here is a PR for the suggestion I made earlier. Personally, it does feel a bit strange putting down HTTP errors in service files 💭  
I did notice that ToolJet is putting down HTTP exception errors [inside their services](https://github.com/ToolJet/ToolJet/blob/a68c727eae7b15d73c4aaacce0d3cf0705c44108/server/src/services/users.service.ts#L112). What do you think about this implementation? 🤔

**Comment by olivierobert** [comment]
I understand where your concerns about pushing the HTTP layers down into service 🤔 I am not an expert in NestJS, so I can't say for sure if that is the best practice. But based on your examples and the fact that services are built into the framework, I would say it would be fine. These exceptions are built into the framework so they beat any custom implementation 👨‍🔧
