### ISSUE TITLE
[Bug] UI is not responsive

### ISSUE THREAD

**Issue by olivierobert** [AetheryNA/google-scraper#53]
## Issue

When using a screen smaller than a standard desktop/laptop screen, the application UI does not resize as expected:

![image](https://user-images.githubusercontent.com/696529/180601054-7a9f145a-8d8c-4573-a3be-a1d0744a8f3f.png)

The main reason is that it missing one essential `meta`:

```
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
```

## Expected

The UI application should be usable on small screen sizes. You can refer to the Tailwind breakpoint information: https://tailwindcss.com/docs/screens

**Comment by AetheryNA** [comment]
Thanks for catching this, I'll fix it right away 👷🏾
