### ISSUE TITLE
[Chore] Rendered HTML must not be rendered inline

### ISSUE THREAD

**Issue by olivierobert** [AetheryNA/google-scraper#54]
## Issue

The scraped context can be viewed at the route `/results/view-html`:

![image](https://user-images.githubusercontent.com/696529/180601260-01d8ac34-4410-40f7-af34-ad944217a2a5.png)

This is not ideal as the content has lots of non-compliant code (e.g., `meta` should be rendered in `body` 😅 ) and poses security risks.

## Expected

The HTML content must be rendered using an iframe. You can refer to the attribute srcdoc: https://www.w3schools.com/tags/att_iframe_srcdoc.asp

**Comment by AetheryNA** [comment]
Oh! Thanks for spotting this also thanks for the resource, I will implement this immediately 🙈

**Comment by AetheryNA** [comment]
Here is the PR for this #60 😸
